version: "3"
services:
  eurekaserver:
    image: eurekaserver
    ports:
      - "8761:8761"
  weatherservice:
    image: weatherservice
    ports:
      - "8081:8081"
    depends_on:
      - eurekaserver
  currencyservice:
    image: currencyservice
    ports:
      - "8082:8082"
    depends_on:
      - eurekaserver
  predict:
    image: predictservice
    ports:
      - "8080:8080"
    depends_on:
      - eurekaserver
      - weatherservice
      - currencyservice
